version: "3"

services:
  providerOne:
    image: ${{ secrets.ALI_NAMESPACE_URL }}/action/provider_one:latest
    ports:
      - "8666:8666"

  gateway:
    image: ${{ secrets.ALI_NAMESPACE_URL }}/action/gateway:latest
    ports:
      - "8080:8080"

  login:
    image: ${{ secrets.ALI_NAMESPACE_URL }}/action/login:latest
    ports:
      - "8000:8000"

  hello:
    image: ${{ secrets.ALI_NAMESPACE_URL }}/action/hello:latest
    ports:
      - "8001:8001"

  providerTwo:
    image: ${{ secrets.ALI_NAMESPACE_URL }}/action/provider_two:latest
    ports:
      - "8667:8667"

  providerThree:
    image: ${{ secrets.ALI_NAMESPACE_URL }}/action/provider_three:latest
    ports:
      - "8668:8668"
